[package]
name = "jolt"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
default-run = "Jolt"

[features]
default = ["desktop"]
cli = []
desktop = ["dep:jolt-ui"]
debug-ui = ["desktop", "jolt-ui/debug-ui"]

[[bin]]
name = "Jolt"
path = "src/main.rs"
required-features = ["desktop"]

[[bin]]
name = "jolt-cli"
path = "src/cli.rs"
required-features = ["cli"]

[dependencies]
jolt-api.workspace = true
jolt-engine.workspace = true
jolt-rpc.workspace = true
jolt-ui = { workspace = true, optional = true }
jolt-update.workspace = true
tokio.workspace = true
futures.workspace = true
clap.workspace = true
mimalloc.workspace = true
anyhow.workspace = true
libc.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
